development:
  adapter: postgresql
  encoding: utf8
  database: recipe
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: recipe
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: recipe
  pool: 5
  timeout: 5000